version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"